export enum TicketType {
  INCIDENT = 'INCIDENT',
  PROBLEM = 'PROBLEM',
  CHANGE_REQUEST = 'CHANGE_REQUEST',
  SERVICE_REQUEST = 'SERVICE_REQUEST',
  QUESTION = 'QUESTION',
  FEEDBACK = 'FEEDBACK',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
